### ISSUE TITLE
Support usage of `.swcrc`

### ISSUE THREAD

**Issue by sar** [vitejs/vite-plugin-react-swc#1]
Add support for usage of external `.swcrc` configuration file as optional parameter passed to `swcReactRefresh()`.

**Example**
```
swcReactRefresh({
  swcrc: true,  // override defaults
}),
```

**Issue**

Swc config appears to be hardcoded in-line and plugin does not respect `.swcrc` in rootDir. For example, adding changes like `"transform" { "legacyDecorator": true }` are not picked up by the plugin.

https://github.com/ArnaudBarre/vite-plugin-swc-react-refresh/blob/95291df10ecc2e1ec076db2f771e03fcd465fa64/src/swc-react-refresh.ts#L45-L62

Is overriding defaults supported (might be documentation issue)?

**Comment by ArnaudBarre** [comment]
This is hardcoded mostly because I did not see the need for a config.

I can add an option, but this plugin is only used in dev, so the build pipeline for vite need to support this as well. Is it the case for you?

If you need this for both dev and build, you can look at https://github.com/egoist/unplugin-swc

**Comment by sar** [comment]
Testing in dev. Some environments require tweaking `swcrc`, it'd be useful to add support for an optional config param.

**Comment by ArnaudBarre** [comment]
Can you tell me if just changing `swcrc` to true in the node_modules does what you expect?
If it works I can make it a plugin parameter, otherwise I need to look a bit more at how config loading & options merging works in swc

**Comment by ArnaudBarre** [comment]
Hi!
After discussion with the core team, we decided to make this plugin official and keep the SWC configuration off.

If someone want to propose a use-case for it, please open a new issue to discuss it.

**Comment by andyrichardson** [comment]
Thanks for your work on this project! Just updated to the new version of Vite and wanted to try this out. 

There is a swc [plugin for styled components](https://www.npmjs.com/package/@swc/plugin-styled-components) but I can't currently use it duebecause of this issue. This wasn't a problem on the babel plugin due to being able to specify plugins

```js
react({
  babel: {
    plugins: [['babel-plugin-styled-components', { pure: true }]],
  },
})
```

**Comment by ArnaudBarre** [comment]
Thanks for reaching out.

We don't plan to support all use cases with this default plugin, but depending on the complexity and the need we could add an option for some use cases that have a good benefits/performance ratio.

Can you tell me if using an `.swcrc` file and changing [this line](https://github.com/vitejs/vite-plugin-react-swc/blob/main/src/index.ts#L53) to rue in your node_modueles works for you?

Letting SWC resolve the configuration would be a good tradeoff, but would still make the caching feature I'm working on a bit more complex.

**Comment by sar** [comment]
> Can you tell me if using an `.swcrc` file and changing [this line](https://github.com/vitejs/vite-plugin-react-swc/blob/main/src/index.ts#L53) to rue in your node_modueles works for you?

Overriding parameter `swcrc: true` in `/node_modules/.../swc-react-refresh.js` does fix it, correctly parses swc config from project root.

**Comment by jrobeson** [comment]
should there be a base swc plugin for configuring this file instead?

**Comment by ArnaudBarre** [comment]
I was a bit optimist yesterday, I totally forgot that this would require more work to support SWC at build time.

Tracking this in https://github.com/vitejs/vite-plugin-react-swc/issues/16
