### ISSUE TITLE
out of bounds memory access

### ISSUE THREAD

**Issue by ar7casper** [vitejs/vite-plugin-react-swc#105]
Hey

I'm using your plugin, and I get `RuntimeError: out of bounds memory access.`
The weird part is that it works fine on my machine but not my colleague's. Although we have identical versions.
Using node 18 / 20. (fails on both)
yarn 1.22.19.
nx 16.1.4
vite 4.3.5

Using Mac m1.

**Comment by ar7casper** [comment]
> Is this something happening on the default template?

Not sure what a default template is 😎

**Comment by ArnaudBarre** [comment]
`yarn crate vite` template TS-SWC

**Comment by ar7casper** [comment]
@ArnaudBarre 

Found the isssue.
Had @swc/core - 1.2.x
And you were using 1.3.58.

The reason it was difficult to track it down is because with 1.3.53 there were no issues....

**Comment by ArnaudBarre** [comment]
Not sure to understand which version of SWC doesn't work for you?
It the latest working? If yes we can close the issue
