### ISSUE TITLE
No options of treating JS as JSX

### ISSUE THREAD

**Issue by Herob527** [vitejs/vite-plugin-react-swc#106]
Currently, I can configure vite esbuild to enforce treating js files as jsx (we have loads of js files with jsx)

But since this plugin disables esbuild options, treating js and jsx separately comes back

**Comment by ArnaudBarre** [comment]
Yes this will not be supported by this plugin. See https://github.com/vitejs/vite-plugin-react-swc/issues/57#issuecomment-1425931254 for more info
