### ISSUE TITLE
Build errors when using SWC plugins

### ISSUE THREAD

**Issue by ohazda** [vitejs/vite-plugin-react-swc#107]
Hey, 

I am not sure what is going wrong but I've tried it on my laptop:

```
MacBook Pro M1 Max
macOS 13.3.1
pnpm 
```

But also I have tried it [CodeSandbox](https://codesandbox.io/p/sandbox/trusting-fog-jm7zfo?file=%2Fvite.config.ts%3A6%2C74)

<img width="1324" alt="Screenshot 2023-05-11 at 11 13 52 AM" src="https://github.com/vitejs/vite-plugin-react-swc/assets/70153084/9a7a8021-0a75-4ef1-9646-b44c4a96aed0">

I am not sure what I am missing here. It is worth mentioning that I have tried the emotion plugin, same thing.

Appreciate any help 🙌🏻

**Comment by ArnaudBarre** [comment]
Yeah not sure SWC works on CodeSandbox

Does this happen with the default template?

Does this happen with you force swc/core to few version below?

**Comment by ohazda** [comment]
@ArnaudBarre Hey, just tried your playground it worked well. Then I bumped @swc/core to 1.3.57 and the tests failed 😞

**Comment by ArnaudBarre** [comment]
Does it breaks only with a specific plugin? Or even without plugin? Maybe there is already an issue on that on the @swc repo

**Comment by ohazda** [comment]
@ArnaudBarre I think it works without plugins. I am not able to find one. But I think we can close this issue, it definitely looks like the upstream. Thank you!
