### ISSUE TITLE
Support vitest experimentalOptimizer

### ISSUE THREAD

**Issue by 79s-net** [vitejs/vite-plugin-react-swc#111]
Edited: Happens when using https://vitest.dev/config/#deps-experimentaloptimizer

**Comment by ArnaudBarre** [comment]
Please use triple quote for sharing code.
Alors this doesn't look like a minimal repro, and not sure the code is valid, react() is used inside `webExtension` and not in the plugin list.

**Comment by ofrades** [comment]
This happens to me if I add:

```
      deps: {
        experimentalOptimizer: {
          enabled: true,
        },
      },
```

to the vitest.config.ts
