### ISSUE TITLE
 Generic React components without props

### ISSUE THREAD

**Issue by flammenmensch** [vitejs/vite-plugin-react-swc#112]
Error `Unexpected token 'RadioGroup'. Expected jsx identifier` when using generics in react components.

The following code produces the error above even though it is a valid tsx:
```typescript
<RadioGroup<string> ...>
  {renderChildren()}
</RadioGroup>
```

**Comment by ArnaudBarre** [comment]
Can you provide a repro? Its working for me in multiple project so probably an issue with an outdated SWC version

**Comment by ArnaudBarre** [comment]
This is a regression in SWC: https://github.com/swc-project/swc/issues/7456
The last working version is `1.3.58`
You can pin the version is via the resolutions/overrides: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides
