### ISSUE TITLE
[vite] Internal server error: Bindings not found.

### ISSUE THREAD

**Issue by Jeyaprabakar01** [vitejs/vite-plugin-react-swc#113]
I followed all the solutions mentioned in the earlier issue, which is similar to this. still getting the same error. I had some issues with my laptop's Windows OS, so I reinstalled it. After that, I only had this issue. before the vite-SVC project worked well. What can I do to resolve this issue?

![react-svc](https://github.com/vitejs/vite-plugin-react-swc/assets/87477850/a53b11ad-71fe-4e43-9236-668f75680385)

![Screenshot 2023-05-30 192118](https://github.com/vitejs/vite-plugin-react-swc/assets/87477850/f6a024af-76fb-4b06-9187-522b7d4b4b10)

**Comment by ArnaudBarre** [comment]
So you still have the error deleting the node_modules and package-lock and then reinstall?

**Comment by Jeyaprabakar01** [comment]
currently I am using pnpm

**Comment by Jeyaprabakar01** [comment]
> Which package manager are you using? Have you tried with another package manager?

I tried with npm also. it throwed same error

**Comment by ArnaudBarre** [comment]
Maybe a regression with swc v1.3.61. Can you check to override with an previous version?

**Comment by Jeyaprabakar01** [comment]
> Maybe a regression with swc v1.3.61. Can you check to override with an previous version?

still throws same error

**Comment by Jeyaprabakar01** [comment]
I deleted and installed the swc stuffs repeately. but finally worked and thank you for the support

**Comment by xielongmei** [comment]
hi,I have got the same problem, can you tell me how you resolve it?

**Comment by codemaker2015** [comment]
Try to install the optional dependencies of SWC:

`npm i -D @swc/cli @swc/core`
