### ISSUE TITLE
Interestingly I'm having the same HMR issue but with react.

### ISSUE THREAD

**Issue by kojoYeboah53i** [vitejs/vite-plugin-react-swc#123]
Interestingly I'm having the same HMR issue but with react. 

If I downgrade to vite@2.6.14 it works as expected. But in the new versions I see the terminal notice but nothing happens in the browser. Replaced it with preact (just to test) and the same thing so I believe the issue might be with vite's HMR or the @preact/preset-vite and/or @vitejs/plugin-react-refresh packages.

_Originally posted by @adrianocr in https://github.com/vitejs/vite/issues/7839#issuecomment-1107706110_

**Comment by kojoYeboah53i** [comment]
update

**Comment by ArnaudBarre** [comment]
Please provide a reproduction
