### ISSUE TITLE
Seeing "failed to handle: failed to invoke plugin" error.

### ISSUE THREAD

**Issue by Matthematic** [vitejs/vite-plugin-react-swc#128]
I am admittedly new to vite, but I can't figure out what is wrong with my configuration. It is a brand new vite scaffolded app, and I just tried to add the jotai swc plugins to support hmr but I'm getting the following error:
![image](https://github.com/vitejs/vite-plugin-react-swc/assets/6292111/56445433-9ece-4023-b7f0-ca505992dfed)

Here is my vite.config.js. Am I doing something incorrectly?

```javascript
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';
import checker from 'vite-plugin-checker';
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react({
      plugins: [
        ['@swc-jotai/debug-label', {}],
        ['@swc-jotai/react-refresh', {}],
      ],
    }),
    checker({
      // e.g. use TypeScript check
      typescript: true,
    }),
  ],
});
```

**Comment by ArnaudBarre** [comment]
Hi! Someone already reported an issue with this plugin without much updates: https://github.com/vitejs/vite-plugin-react-swc/discussions/103

I don't think I can do anything there, I think it's an issue on the plugin or SWC side

**Comment by ArnaudBarre** [comment]
Closing as unactionable on this repo.
