### ISSUE TITLE
I encountered some issues while using the "@lingui/swc-plugin" plugin.

### ISSUE THREAD

**Issue by shlroland** [vitejs/vite-plugin-react-swc#133]
related issue https://github.com/lingui/swc-plugin/issues/61

Now I use this resolutions to fix it.
<img width="313" alt="image" src="https://github.com/vitejs/vite-plugin-react-swc/assets/45024986/1ba0c8ac-bdbd-4649-a3d9-74e3d63994de">
 
So update deps could resolve this problem?

**Comment by ArnaudBarre** [comment]
Did you use the latest version of the plugin?
It seems that there is nothing I can do here

**Comment by shlroland** [comment]
> Did you use the latest version of the plugin? It seems that there is nothing I can do here

Yes. But why the version of @swc/core is 1.3.61
<img width="996" alt="image" src="https://github.com/vitejs/vite-plugin-react-swc/assets/45024986/c6da375e-da36-4864-a7a1-d8fa32962194">

**Comment by ArnaudBarre** [comment]
Because this was the latest version available on released. It's using a `^` so that's not an issue
