### ISSUE TITLE
Unable to resolve plugins in pnpm with `hoist=false`

### ISSUE THREAD

**Issue by liningpan** [vitejs/vite-plugin-react-swc#135]
I'm trying to use `@graphql-codegen/client-preset-swc-plugin` in a pnpm / Bazel monorepo. It appears that with `hoist=false`, which is also the behavior of the Bazel rules. I get an error like this 

```
Error: Cannot find module '@graphql-codegen/client-preset-swc-plugin'
```

I know storybook had similar issues before, and this is how they resolve modules with absolute paths

```
import { join, dirname } from "path";

function getAbsolutePath(value: string): any {
  return dirname(require.resolve(join(value, "package.json")));
}
const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    getAbsolutePath("@storybook/addon-links"),
  ...
}
```

**Comment by ArnaudBarre** [comment]
Hi,

I not sure this plugin is the best place to fix this kind of resolution issues. I need to get a better understanding at the issue but this plugin is just calling SWC like most other tools would do and I think it should be either better supported by SWC or pnpm
