### ISSUE TITLE
JSX Namespace is disabled by default because react does not support it yet. You can specify jsc.transform.react.throwIfNamespace to false to override default behavior

### ISSUE THREAD

**Issue by one-dragon** [vitejs/vite-plugin-react-swc#137]
写了个加载svg的组件，并使用vite-plugin-svg-icons插件加载svg目录下的所有svg
但在@vitejs/plugin-react-swc插件编译的时候报错，如下图：
![image](https://github.com/vitejs/vite-plugin-react-swc/assets/20273665/cb09db9c-346a-4dc3-bb95-41f7eb74a4f8)

**Comment by one-dragon** [comment]
并且看@vitejs/plugin-react-swc这个插件源码中好像不引入swc的配置文件  导入无法配置当前选项 请问如何解决~

**Comment by LbhFront-end** [comment]
> 并且看@vitejs/plugin-react-swc这个插件源码中好像不引入swc的配置文件 导入无法配置当前选项 请问如何解决~

你好，我想问一下，后面这个问题怎么解决的，有其他方式吗
