### ISSUE TITLE
Tree-shaking

### ISSUE THREAD

**Issue by timsofteng** [vitejs/vite-plugin-react-swc#148]
Hello. May I somehow enable tree-shaking?

**Comment by ArnaudBarre** [comment]
Tree shaking is enabled by default by rollup when doing `vite build`. This plugin doesn't have anything do to with build optimizations.

**Comment by timsofteng** [comment]
@ArnaudBarre is it possible to enable it in dev server?

**Comment by ArnaudBarre** [comment]
Nope that's not how Vite works currently
