### ISSUE TITLE
"ReferenceError: foo is not defined" after upgrading to 3.4.0

### ISSUE THREAD

**Issue by Kamahl19** [vitejs/vite-plugin-react-swc#153]
After upgrading from 3.3.2 to 3.4.0 I am getting "ReferenceError: theme is not defined" when importing theme from Antd https://github.com/Kamahl19/react-starter/blob/main/src/common/styleUtils.ts#L3 . It seems it's caused by changes in @swc/core version 1.3.89

https://github.com/swc-project/swc/issues/8007

**Comment by Kamahl19** [comment]
It seems it's causes by changed in @swc/core version 1.3.89

**Comment by ArnaudBarre** [comment]
This was resolved upstream, closing

**Comment by Kamahl19** [comment]
@ArnaudBarre could you please release a new version with this fix? Thanks!

**Comment by ArnaudBarre** [comment]
The command depend on your pacage manager but you can bump the SWC version in your node_module without having a new version of the package. And probably doing `remove @vitejs/plugin-react-swc && add @vitejs/plugin-react-swc` should work
