### ISSUE TITLE
Feature: ability to unset/change built-in defines

### ISSUE THREAD

**Issue by pc-erin** [vitejs/vite-plugin-react-swc#156]
There's an issue with some libraries that, instead of using `process.env.NODE_ENV` they use `globalThis.process.env.NODE_ENV`, and, and the default define behavior (not sure if it's this plugin or SWC) results in code like `globalThis."development" === "development"`.

See: https://github.com/graphql/graphql-js/issues/3928

I've tried to override this behavior using vite's `define` config option, but it doesn't seem to work.

**Comment by ArnaudBarre** [comment]
This is working at least when in source code in dev. Probably a mismatch from Vite at build time or optimize deps time. Please open an issue with a small repro on stackblitz on the Vite core repo
