### ISSUE TITLE
Support SWC configuration 

### ISSUE THREAD

**Issue by ArnaudBarre** [vitejs/vite-plugin-react-swc#16]
The current version of the plugin is used only in development.

Adding SWC configuration requires to also run it during the build phase.

This require some work, but could be done if there is enough people asking for it (please like the issue and don't comment `+1`).

We don't plan to support every use case, the babel plugin will still be available for people who want to keep using classic runtime for example.

Use cases for it:
  - [decorators](https://github.com/vitejs/vite-plugin-react-swc/issues/15)
  - [styled-component](https://www.npmjs.com/package/@swc/plugin-styled-components)
  - [relay](https://github.com/vitejs/vite-plugin-react-swc/pull/17)
  
  
## Update:

A beta release is available with support for decorators in TS and plugins via the JS API: https://github.com/vitejs/vite-plugin-react-swc/releases/tag/v3.1.0-beta.2

`.swcrc` or other configuration are not supported for now. The goal is to keep the configuration surface small so that I can support most use cases and still enable caching later on. If your need is not currently covered, share it in comment.

**Comment by jurosh** [comment]
This is super needed for styled comps. Eg. to add names to styled components and make inspecting elements easy.
This worked in non-swc:

    babel: { plugins: [['babel-plugin-styled-components', { ssr: false, pure: true, displayName: true, fileName: true }]]  }

**Comment by glekner** [comment]
This looks like a needed addition

**Comment by eyalw** [comment]
+1

**Comment by UzEE** [comment]
This will be extremely useful for enabling decorator support as well. As it stands, we aren't able to migrate our codebase over from Webpack + Babel since we can't take advantage of fast refreshes enabled by SWC.

**Comment by PlayGuitar-CoderQ** [comment]
> This will be extremely useful for enabling decorator support as well. As it stands, we aren't able to migrate our codebase over from Webpack + Babel since we can't take advantage of fast refreshes enabled by SWC.这对于启用装饰器支持也非常有用。就目前而言，我们无法将我们的代码库从 Webpack Babel 迁移过来，因为我们无法利用 SWC 启用的快速刷新。

Our team is also stuck in this place

**Comment by jrobeson** [comment]
@UzEE @PlayGuitar-CoderQ The readme shows you can enable ts decorators, but I've never tried it: https://github.com/vitejs/vite-plugin-react-swc#tsdecorators

**Comment by UzEE** [comment]
@jrobeson Yes, the support was added recently into the main branch, so I'm hopeful it will land at least in an alpha or a beta release soon.

**Comment by notmedia** [comment]
@ArnaudBarre Hi! Could you publish new release for us? We are waiting for decorators support 🙏

**Comment by ArnaudBarre** [comment]
A beta release is available: [3.1.0-beta.2](https://www.npmjs.com/package/@vitejs/plugin-react-swc/v/3.1.0-beta.2)

**Comment by guoyunhe** [comment]
@ArnaudBarre I tried 3.1.0-beta.2, with `react({ tsDecorators: true })` but I still throw errors when compiling:

```
10:27:32 AM [vite] Internal server error: 
  × Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key
   ╭─[/home/admin/workbench/test-obx/src/model.ts:2:1]
 2 │ 
 3 │ export default class BizModel extends Model {
 4 │   formRef: any = null;
 5 │   @obx formData: { list: any[] } = {
   ·   ─
 6 │     list: [{}],
 7 │   };
 8 │   @obx loading = false;
```

**Comment by guoyunhe** [comment]
Can you make a production release of 3.1.0?

**Comment by ArnaudBarre** [comment]
I'm closing this issue with the release of 3.1 that makes tsDecorators and plugins stable.
If you have new configuration needs open a new issue to present your use case and discuss it!
