### ISSUE TITLE
@react-refresh throw "React refresh runtime was loaded twice. Maybe you forgot the base path?" when the page load more than one react-swc vite instance.

### ISSUE THREAD

**Issue by pakholeung37** [vitejs/vite-plugin-react-swc#169]
In the 'refresh-runtime.js' file, this code is meant to prevent loading 'refresh-runtime' twice.
However, after commenting it out, I found that the application still runs perfectly.
```typescript
if (window.$RefreshReg$) {
  throw new Error(
    "React refresh runtime was loaded twice. Maybe you forgot the base path?"
  );
}
``` 
I made a repo to reproduce this. https://github.com/pakholeung37/double-vite-instance-demo

**Comment by ArnaudBarre** [comment]
The application will run correctly but HMR will be broken.
"Micro-frontend" is not supported. The right way to this in Vite is to use one instance and to merge apps via sources (i.e. 
`<script type="module" src="../app-2/src/main.tsx"></script>`)

**Comment by pakholeung37** [comment]
> The application will run correctly but HMR will be broken. "Micro-frontend" is not supported. The right way to this in Vite is to use one instance and to merge apps via sources (i.e. `<script type="module" src="../app-2/src/main.tsx"></script>`)

The current path cannot be resolved, and it resolves as 'localhost:8080/app-2/src/main.tsx.' Regarding the HMR problem, while it would be great if it worked, even if it remains broken, it is acceptable.

**Comment by ArnaudBarre** [comment]
Ah yeah I see so you can instead have `<script type="module" src="src/app.tsx"></script>` and in `app2.tsx` have `import "../../app-2/src/main.tsx"`

**Comment by maziar-dandc** [comment]
I'm just commenting this for future-me:

This error can also happen if `RefreshRuntime` is imported from a domain that is different from rest of vite imports. E.g: `localhost` vs `0.0.0.0` vs `[::]`

**Comment by nguyenbatranvan** [comment]
issue from plugin `@vitejs/plugin-react-swc`

**Comment by talkohavy** [comment]
At least with `@vitejs/plugin-react` it's solvable.

On the remote, make your `vite.config` look like this:

```ts
import { defineConfig, PluginOption } from 'vite';
import react from '@vitejs/plugin-react';
import { federation } from '@module-federation/vite';

function getSingleReactRefreshPlugin(): PluginOption {
  return {
    name: 'single-react-refresh', // Name for the plugin
    enforce: 'pre', // Run this plugin before other transformations
    transform(code, id) {
      if (/\.(js|ts|jsx|tsx)$/.test(id)) {
        const updatedCode = code.replace(
          /import RefreshRuntime from "\/@react-refresh";/g,
          `import RefreshRuntime from "http://localhost:3000/@react-refresh";`,
        );
        return updatedCode;
      }
      return null; // Return null if no transformation is applied
    },
  };
}

export default defineConfig({
  base: 'http://localhost:3001',
  plugins: [
    react(),
    getSingleReactRefreshPlugin(),
    federation({
      name: 'mf_books',
      filename: 'remoteEntry.js',
      exposes: {
        './App': './src/exposes/ExposedBooksMF',
      },
      shared: ['react', 'react-dom', 'react-refresh'],
    })
  ],
  server: {
    port: 3001,
  },
  build: {
    modulePreload: false,
    target: 'esnext',
    minify: false,
    cssCodeSplit: false,
  },
});
```

Can't you make a solution like the above?
