### ISSUE TITLE
HMR doesn't work when a `base` property is set in the Vite config

### ISSUE THREAD

**Issue by nekusu** [vitejs/vite-plugin-react-swc#18]
### Issue

When setting a [base](https://vitejs.dev/config/shared-options.html#base) property in `vite.config.ts` other than the default, HMR does not reflect the changes. Vite logs `[vite] hmr update (modified file)`, but there is no update at all.

### Config example

```ts
import react from '@vitejs/plugin-react-swc';
import { defineConfig } from 'vite';

export default defineConfig({
  base: '/test/',
  plugins: [react()],
});
```

### Notes

This same scenario works as expected when using the babel-based plugin `@vitejs/plugin-react`.

**Comment by ArnaudBarre** [comment]
Thanks for the report!

This will be available in the next path probably next this week.
