### ISSUE TITLE
Add swc minification support

### ISSUE THREAD

**Issue by twk3** [vitejs/vite-plugin-react-swc#185]
Having minify support in a well maintained vite plugin would be great.

In my current use-case I am migrating a craco react project over to vite, and the setup was already using swc for all build and minification. 

The build time mattered beyond dev mode of the react package, as it was also being used in several other packages that developers  and CI is working across at the same time, (an express server, electron app, and mobile focused apps)

**Comment by ArnaudBarre** [comment]
Minification is done by Vite core, the option should be added there along with terser and esbuild.
I'm not sure you will gain much for build time perf given that esbuild is already pretty fast for that job, so while the issue will be welcome, I don't think it will be implemented until someone that wants it adds support with a PR.
