### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by miroirstudiosrl** [vitejs/vite-plugin-react-swc#211]
When I try to install the package using yarn (v2) I get the following error:
`Error: @swc/types@workspace:^: Workspace not found (@swc/types@workspace:^)`

Things I alreay tried:

- Removing yarn cache and yarn.lock and reinstalling everything
- Manually installig @swc/core@1.5.7

**Comment by DiFuks** [comment]
I have a similar problem - tried different versions of yarn, clearing the cache, installing @swc/core, creating a project from scratch.

**Comment by ArnaudBarre** [comment]
Other people are saying v1.5.7 is fine and v1.5.11 was the issue

**Comment by DiFuks** [comment]
Indeed, this workaround works for me:

```

	"resolutions": {
		"@swc/core": "1.5.7"
	},
	"devDependencies": {
		"@vitejs/plugin-react-swc": "3.7.0"
	}
```

**Comment by miroirstudiosrl** [comment]
> Other people are saying v1.5.7 is fine and v1.5.11 was the issue

Yep I've read the issue in the swc repo but nothing I tried has worked

**Comment by miroirstudiosrl** [comment]
> Indeed, this workaround works for me:
> 
> ```json
> "resolutions": {
>   "@swc/core": "1.5.7"
> },
> "devDependencies": {
>   "@vitejs/plugin-react-swc": "3.7.0"
> }
> ```

Thanks this works 💪
