### ISSUE TITLE
Add styled-component configuration to the config

### ISSUE THREAD

**Issue by yarinsa** [vitejs/vite-plugin-react-swc#22]
Using babel we used to have the following configuration 
```
[
  'babel-plugin-styled-components',
  {
    displayName: !(command === 'build'),
    fileName: false,
  },
],
```
To present class names while still in development. Using vercel SWC we can't. 
Found this [issue](https://github.com/vercel/next.js/issues/30802). So I think that [this](https://github.com/vitejs/vite-plugin-react-swc/issues/16) might solve it, but not familiar enough. If that's the case this issue can be closed

**Comment by ArnaudBarre** [comment]
Yes that's one of the main use cases for #16. You can subscribe to be notified I have made some progress on it
