### ISSUE TITLE
Syntax errors in Terminal

### ISSUE THREAD

**Issue by LKessell** [vitejs/vite-plugin-react-swc#224]
I began seeing many of these syntax errors in the terminal when starting up my Vite app:
![image](https://github.com/user-attachments/assets/86ef3cd7-db53-40a2-9ea6-f97bacab9ca7)

I am using version 3.6.0 of the vite-plugin-swc package, and am seeing the errors on both Windows 10 and Windows 11. Upgrading the package to 3.7.0 has not resolved the issue.
Errors are reported in the terminal, but my app still runs/builds without issue and seems to work as expected.

Thank you!

**Comment by ArnaudBarre** [comment]
Do you use plugins?
This is probably related to the v1.7 of SWC.

**Comment by LKessell** [comment]
Hi there, yes I am using a few plugins in addition to this one. @vitejs/plugin-basic-ssl, vite-plugin-node-polyfills, and vite-plugin-svgr
All are updated to the most recent versions, but it does look like v1.7 of SWC was released more recently

**Comment by ArnaudBarre** [comment]
Yeah SWC plugins need an update after 1.7, see this tweet: https://twitter.com/kdy1dev/status/1813796117513191923
This is sad but they are still considered an experimental API

**Comment by ArnaudBarre** [comment]
I suspect that with the low activity here this has been fixed in SWC!
