### ISSUE TITLE
Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key

### ISSUE THREAD

**Issue by Zhengy1995** [vitejs/vite-plugin-react-swc#24]
When I replace `@vitejs/plugin-react` with `@vitejs/plugin-react-swc`, it doesn't work well,why or how to config to supports decorator?
![image](https://user-images.githubusercontent.com/30064447/207489750-b03c3ed1-2cd5-456a-a1a5-936e8165831d.png)

**Comment by steveruizok** [comment]
Dropping the fix for future travelers:

```ts
// vite.config.ts

import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'

export default defineConfig({
	plugins: [react({ tsDecorators: true })],
	optimizeDeps: {
		esbuildOptions: {
			tsconfig: './tsconfig.json',
		},
	},
})
```
