### ISSUE TITLE
support jsxImportSsource @emotion/react?

### ISSUE THREAD

**Issue by Dimitri-WEI-Lingfeng** [vitejs/vite-plugin-react-swc#25]

**Comment by dchambers** [comment]
It just so happens that @sanderdrummer created a branch to do exactly this (as a temporary work-around) just one hour after you created this issue ❤️ . What's even better he also published it to npm as [plugin-react-swc-emotion](https://www.npmjs.com/package/plugin-react-swc-emotion).

Simply switch from `@vitejs/plugin-react-swc` to `plugin-react-swc-emotion` in your `package.jsonj`, and then change the import statement in `vite.config.ts` to point to `plugin-react-swc-emotion`.

**Comment by ArnaudBarre** [comment]
Sounds good for me. I will work on this later today
