### ISSUE TITLE
HMR is not working when `base` option in vite.config.ts is not `'/'`

### ISSUE THREAD

**Issue by wand2016** [vitejs/vite-plugin-react-swc#27]
```diff
  export default defineConfig({
-   base: '/',
+   base: '/elsewhere/',
    ...
```

HMR is not working when `base` option in vite.config.ts is not `'/'`.

**Comment by ArnaudBarre** [comment]
Duplicate of #18, fixed in main, will be available in next patch (probably in a few days)!
