### ISSUE TITLE
How to remove data-testid

### ISSUE THREAD

**Issue by ruiaraujo012** [vitejs/vite-plugin-react-swc#30]
Is there any option to remove the `data-testid` from the build bundle?
Could I use a swc plugin like this: [plugin](https://www.npmjs.com/package/swc-plugin-react-remove-properties).
If yes, how?

**Comment by ArnaudBarre** [comment]
Yeah this probably require to use a plugin. This is not supported ATM, tacked in https://github.com/vitejs/vite-plugin-react-swc/issues/16
