### ISSUE TITLE
Debug is broken when use CRLF line break

### ISSUE THREAD

**Issue by fifv** [vitejs/vite-plugin-react-swc#31]
Reproduce:

1. `yarn create vite` with React and Typescript

2. edit `App.tsx` like this:

```typescript
/* 


these empty lines in the comment block will break debugging



*/

export default function App() {
	console.log('App');  // breakpoint here
	return (
		<div>
			test
		</div>
	)
}
```

4. Change `App.tsx` line break to CRLF
5. Set breakpoint at line `console.log('App');`
6. Start debug, but breakpoint hit at a weird place:
![image](https://user-images.githubusercontent.com/75289510/208642120-3de72e71-c0a3-4eb3-a166-3ada7912bb8c.png)
If set breakpoint at devtool, it get misplaced.
![image](https://user-images.githubusercontent.com/75289510/208642964-24769e4b-02aa-4188-88db-e70344f88fc1.png)

- I have tested `//` comment and function to consume top lines, but seems only `/* */` break debug.
- If change line break to LF, everything is fine.
- [vite-plugin-react](https://github.com/vitejs/vite-plugin-react) has no such problem.

Here is my `launch.json`:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:5173",
      "webRoot": "${workspaceFolder}/src" // This works, but i still don't know why after a lot of search. CRA and esbuild+liveserver also only works with this path.
    }
  ]
}
```
`vite.config.ts`
```typescript
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'
export default defineConfig({
  plugins: [react()],
  server: {
    host: '0.0.0.0' // the default 'localhost' makes browser and vscode fails to fetch sourcemap, due to some CORS error, idk why.
  }
})
```
Sysinfo:
<details>
<summary>Click to expand!</summary>

```
  System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 10.07 GB / 31.87 GB
  Binaries:
    Node: 18.12.1 - ~\AppData\Local\Temp\xfs-dce58dc0\node.CMD
    Yarn: 3.3.0 - ~\AppData\Local\Temp\xfs-dce58dc0\yarn.CMD
    npm: 7.24.1 - D:\Documents\_JavaScript\node_global\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1037.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react-swc: ^3.0.0 => 3.0.1 
    vite: ^4.0.0 => 4.0.2 
```

</details>

**Comment by ArnaudBarre** [comment]
Blocked by upstream: https://github.com/swc-project/swc/issues/6694

kdy1 assigned recently so maybe this can be fixed quickly. 

Keeping open, but I would advice using linux line break everywhere anyway. I think this can be enforced by Prettier or git.

**Comment by ArnaudBarre** [comment]
Fixed upstream
