### ISSUE TITLE
I found an error when using a method decorator

### ISSUE THREAD

**Issue by PlayGuitar-CoderQ** [vitejs/vite-plugin-react-swc#36]
This is my project dependency :

<img width="328" alt="image" src="https://user-images.githubusercontent.com/55419399/210827968-31ea6714-feca-47d2-be70-7e6eaca01562.png">

This is the faulty code:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/55419399/210827755-2bdc459a-297c-4fca-bbe2-7bdb9f1d7a4c.png">

**Comment by ArnaudBarre** [comment]
Decorator are not supported by default. Tracked in #16
