### ISSUE TITLE
Why I still see [BABEL] error?

### ISSUE THREAD

**Issue by timsofteng** [vitejs/vite-plugin-react-swc#42]
Hello. If I've got correctly this plugin change the babel to swc.
But I still have babel error when I run vite as dev server

```

  VITE v4.0.4  ready in 323 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.33.5:5173/
  ➜  press h to show help
[BABEL] Note: The code generator has deoptimised the styling of /home/my/project/src/assets/404-background.svg as it exceeds the max of 500KB.
```

**Comment by ArnaudBarre** [comment]
You are probably using vite-plugin-svgr which uses svgr which uses Babel to transform SVG to React component.

And probably this SVG is too big or somehting. You can try to run sgvo on it (here as a webapp: https://jakearchibald.github.io/svgomg/)

Personally I'm using https://github.com/ArnaudBarre/vite-plugin-fast-react-svg for SVGs but this require very clean SVGs because no transform is applied

**Comment by timsofteng** [comment]
> You are probably using vite-plugin-svgr which uses svgr which uses Babel to transform SVG to React component.
> 
> And probably this SVG is too big or somehting. You can try to run sgvo on it (here as a webapp: https://jakearchibald.github.io/svgomg/)
> 
> Personally I'm using https://github.com/ArnaudBarre/vite-plugin-fast-react-svg for SVGs but this require very clean SVGs because no transform is applied

You are absolutely right.
I use this plugin.
Thanks. So the only two possible way are using one those plugins?

**Comment by ArnaudBarre** [comment]
If you want SVG as React component, you need a plugin. Otherwise you can import it the same way as png/jpg source (but you loose some capabilities from SVG)

There are maybe other plugin that do the same things but nothing convincing for me when I wrote this plugin last year

**Comment by timsofteng** [comment]
Thank you. I guess this issue is closed.

**Comment by ArnaudBarre** [comment]
Without an error it's complex. But you can first see why babel is in your project by runining `npm why @babel/core` of similar
