### ISSUE TITLE
Vite 4 with SSR: HMR not working

### ISSUE THREAD

**Issue by jvanmaaren** [vitejs/vite-plugin-react-swc#46]
### Describe the bug

**Description:**
For the default setup created by "yarn create vite-extra" (with SSR) HMR does not work

**Expectation:**
When I change a text in App.tsx, I should immediately see the change in my browser

### Reproduction

https://github.com/jvanmaaren/vite4-react-ssr

### Steps to reproduce

- `yarn create vite-extra` (ssr+react, typescript + SWC)
- `yarn install`
- yarn dev
- change some text in App.tsx
- The browser console will say "[vite] hot updated: /src/App.tsx"
- But the text will not be updated

You can also see the problem in this sandbox:
https://codesandbox.io/p/github/jorgvm/vite4-react-ssr/draft/boring-cherry

All files were created by the "yarn create vite-extra" command

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 10.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Chrome Canary: 111.0.5560.0
    Edge: 109.0.1518.61
    Firefox: 109.0
    Safari: 16.3
  npmPackages:
    @vitejs/plugin-react-swc: ^3.0.0 => 3.0.1
    vite: ^4.0.0 => 4.0.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jvanmaaren** [comment]
thanks!

**Comment by ArnaudBarre** [comment]
This will be available in next stable version, release Tuesday with Vite 4.1 if everything goes well
