### ISSUE TITLE
Support MDX

### ISSUE THREAD

**Issue by ArnaudBarre** [vitejs/vite-plugin-react-swc#52]
Re: https://github.com/storybookjs/builder-vite/pull/552

**Comment by IanVS** [comment]
I haven't looked into whether this is an issue with the way Storybook is rendering MDX or this plugin itself.

**Comment by ArnaudBarre** [comment]
I think this would work because mdx output runnable JS but fast refresh will not work

**Comment by IanVS** [comment]
Yeah it was indeed a bug in Storybook, that should be fixed in https://github.com/storybookjs/builder-vite/pull/556.  I've tested it in our examples, and it works fine.  fast-refresh might not work, but the reload is nice and fast.
