### ISSUE TITLE
Support TS/JSX inside node_modules

### ISSUE THREAD

**Issue by spa5k** [vitejs/vite-plugin-react-swc#53]
[plugin:vite:import-glob] Invalid glob import syntax: Expect CallExpression, got BinaryExpression

```
F:/app/node_modules/.pnpm/generouted@1.7.2_vite@4.1.1/node_modules/generouted/src/react-location.tsx:9:19

7  |  type Module = { default: Element; Loader: LoaderFn; PendingElement: Element; ErrorElement: Element }
8  |  
9  |  const PRESERVED = import.meta.glob<Module>('/src/pages/(_app|404).{jsx,tsx}', { eager: true })
   |                    ^
10 |  const ROUTES = import.meta.glob<Module>(['/src/pages/**/[\\w[]*.{jsx,tsx}', '!**/(_app|404).*'])
11 |
```

## How to reproduce-

1. Clone this example - https://github.com/oedotme/generouted/tree/main/examples/react-location/nested-layouts
2. Update vite config to use plugin-react-swc rather than the original one, you will get the error.

**Comment by ArnaudBarre** [comment]
Hi,

I checkout the repo and tried it to migrate to SWC. I got another issue about cannot resolving react. This make sense because it's used inside your main project without having it as a dev-dependency. Adding react & react-dom as dev-deps works.

**Comment by vallerydelexy** [comment]
> Hi,
> 
> I checkout the repo and tried it to migrate to SWC. I got another issue about cannot resolving react. This make sense because it's used inside your main project without having it as a dev-dependency. Adding react & react-dom as dev-deps works.

not sure what do you mean by 
> Adding react & react-dom as dev-deps works.

but its not working
![image](https://user-images.githubusercontent.com/17786532/219879734-89a274e1-681e-4981-ae9e-3b6a163a1505.png)

**Comment by ArnaudBarre** [comment]
I mean adding dev dependency here: https://github.com/oedotme/generouted/blob/main/packages/generouted/package.json

**Comment by spa5k** [comment]
@vallerydelexy fixed in https://github.com/oedotme/generouted/releases/tag/v1.7.16

**Comment by HarunKilic** [comment]
Not sure if that fixed the issue with Glob, but i'm still having the main issue with the latest package. 

Vite: v4.1.4
@vitejs/plugin-react-swc: v3.2.0
React+-dom: v18.2.0
Generouted: v1.7.16

**Comment by ArnaudBarre** [comment]
Can you provide a minimal repro?
The first repro was inside the monorepo which is a special case that was fixed

**Comment by ArnaudBarre** [comment]
Thanks for the repro.
So the package ships raw TSX with Vite globs into node_modules.
For now this plugins does not transpile node modules, that why you get this error. This is a two lines patch if you want to workaround for now.
Vite takes care not inluding this into deps prebundling, I will see with the team if we should support this pattern or not

**Comment by spa5k** [comment]
Can you mention the patch for it? I tried optimized deps, but it didn't seem to work.

**Comment by ArnaudBarre** [comment]
You need to `if (id.includes("node_modules")) return;`

This might be something that change in the future, I need to look on how it plays with deps prebundling (on the repo it seems that the file is not part of dependencies pre-bundling)

**Comment by HarunKilic** [comment]
> You need to `if (id.includes("node_modules")) return;`
> 
> This might be something that change in the future, I need to look on how it plays with deps prebundling (on the repo it seems that the file is not part of dependencies pre-bundling)

Can you be a bit more specific about the patch fix? 
What do we need to do? Add or remove the highlighted value? And where? In which package? 
Thanks

**Comment by ArnaudBarre** [comment]
You need to find this line in the compiled version (cjs or mjs depending on your package.json): https://github.com/vitejs/vite-plugin-react-swc/blob/main/src/index.ts#L154

**Comment by opeologist** [comment]
any way to get this into the plugin instead of having to patch it?

**Comment by ArnaudBarre** [comment]
Hi,


Fixed in https://github.com/vitejs/vite-plugin-react-swc/commit/4b9b2d5958adea17398ed569a356821845b55726.

Note that for now this not supported by TS and errors from these files cannot be silenced if the user is using a stricter configuration than the library author: https://github.com/microsoft/TypeScript/issues/30511. I advise to use it only for internal libraries for now.
