### ISSUE TITLE
Component selectors can only be used in conjunction with @emotion/babel-plugin, the swc Emotion plugin, or another Emotion-aware compiler transform.

### ISSUE THREAD

**Issue by rs-8** [vitejs/vite-plugin-react-swc#54]
Hello!
Have issue described above.

[Link to similar issue in swc](https://github.com/swc-project/swc/issues/4065)

**Comment by ArnaudBarre** [comment]
Hi,

The issue you linked is pretty clear and well tracked.

This project only allow you to use SWC plugins and is not a tracker for all the various missing features of these plugins.
