### ISSUE TITLE
Support decorators in JS files

### ISSUE THREAD

**Issue by meetajhu** [vitejs/vite-plugin-react-swc#60]
I went through the docs/issues and there is a no clear way on how to add decorator support for Mobx or is it even supported? I am not using Typescript.

From this [docs](https://swc.rs/docs/configuration/compilation) i tried passing like this in below config: 

```
import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react-swc'
import svgrPlugin from 'vite-plugin-svgr';
import { splitVendorChunkPlugin } from 'vite';
import * as path from 'path';
import jsconfigPaths from 'vite-jsconfig-paths'
import { createHtmlPlugin } from 'vite-plugin-html'

export default defineConfig(({ mode }) => {

  const env = loadEnv(mode, process.cwd())

  return {
    plugins: [react(
      {
          "decorators": true,
          "decoratorsBeforeExport": true,
      }
    ), svgrPlugin(), jsconfigPaths(), splitVendorChunkPlugin(),
    createHtmlPlugin({
      minify: true,
      inject: {
        data: {
          reactenv: env.REACT_APP_ACTUAL_ENV,
        }
      }
    })
  ],
  define: { //Handle prcoess.env
    'process.env': {}
  },
  }});
```
  
  i keep getting error in console `this.example` is undefined

**Comment by ArnaudBarre** [comment]
Yes this is not supported ATM. JS files are sent untranspiled in dev to the browser and this feature is not supported by esbuild. This is technically possible to add support for this, but I'm not sure this is a good idea.
This should be possible with the Babel plugin

**Comment by ArnaudBarre** [comment]
Hi!
I discussed this with the team and for now we like the fact that pure JS code is sent unstranspiled to the browser in dev mode. If your codebase is small the babel plugin will probably be as fast as the SWC one. And if for large codebases, I really invite you to migrate to TS, this is really worth the initial learning curve in the long run.

**Comment by meetajhu** [comment]
> Hi! I discussed this with the team and for now we like the fact that pure JS code is sent unstranspiled to the browser in dev mode. If your codebase is small the babel plugin will probably be as fast as the SWC one. And if for large codebases, I really invite you to migrate to TS, this is really worth the initial learning curve in the long run.

Yup its a large one. Sure will work on it.
