### ISSUE TITLE
Not able to specify target

### ISSUE THREAD

**Issue by danielwalczak** [vitejs/vite-plugin-react-swc#84]
In my project, I'm using features from es2022 spec, and Im not able to specify that using this plugin.

It would be great to specify any swc/jsc options.

**Comment by ArnaudBarre** [comment]
By default SWC should handle any recent spec compliant syntax.
The compile target in dev is es2020 (for what can be downlevel, not the case for all features and no polyfill is provided)

For builds, esbuild (from core) is used and can be configured with [build.target](https://vitejs.dev/config/build-options.html#build-target)

**Comment by ArnaudBarre** [comment]
Closing as I think the question has been answered.

**Comment by HelloWorld017** [comment]
If the `plugin` is specified, `vite-plugin-react-swc` is used for the build phase, too. So it would be great to allow specifying the `target` option, for users who are using the `plugin` option.
