### ISSUE TITLE
How to configure SWC options? To use Stage 3 decorators, for example.

### ISSUE THREAD

**Issue by yay** [vitejs/vite-plugin-react-swc#85]
Hi,

Basically the question is this:

How can I test SWC Stage 3 decorator support when using React SWC plugin?

Some background:

SWC recently shipped with Stage 3 decorator support: https://swc.rs/docs/configuration/compilation#jsctransformdecoratorversion

I'd like to try it out with React SWC plugin, but I don't see where to pass those options. Simply creating `.swcrc` file (with the following contents) at the root of the project does nothing:

```
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "decorators": true
    },
    "transform": {
      "decoratorVersion": "2022-03"
    }
  }
}
```

I also don't see a config to pass SWC options to the React SWC plugin:

```ts
import { PluginOption } from "vite";
type Options = {
    /**
     * Control where the JSX factory is imported from.
     * @default "react"
     */
    jsxImportSource?: string;
    /**
     * Enable TypeScript decorators. Requires experimentalDecorators in tsconfig.
     * @default false
     */
    tsDecorators?: boolean;
    /**
     * Use SWC plugins. Enable SWC at build time.
     * @default undefined
     */
    plugins?: [string, Record<string, any>][];
};
declare const react: (_options?: Options) => PluginOption[];
export default react;
```

I would expect being able to pass SWC options to the React SWC plugin like so, if the options in `.swcrc` file are not picked up when using SWC via the React SWC plugin:

```ts
plugins: [react({
  swcOptions: {
    "jsc": {
      "parser": {
        "syntax": "ecmascript",
        "decorators": true
      },
      "transform": {
        "decoratorVersion": "2022-03"
      }
    }
  }
})],
```

Any help is appreciated!

**Comment by ArnaudBarre** [comment]
Hi, 

We decided to not support decorators for JS files: https://github.com/vitejs/vite-plugin-react-swc/issues/60#issuecomment-1484278954

Seeing how much this spec has changed make me confortable with the idea that this should not be easy to use until shipped browser.

If you really want to use it with pure JS, the plugin is easy to patch

**Comment by yay** [comment]
@ArnaudBarre Thank you for your quick response. I'm actually trying to make use of Stage 3 decorators in a TypeScript (v5) project. From my understanding, Stage 3 decorators are transpiled to JS code that works in current browsers, as can be seen in the following [example](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAGzgczQUwCYFlNQAWc2AFHAE4xoxgCGy+RJAXInWAJ4A0iA+hARRMADyhsOnAJSIA3gCh5iZYlCRYCRBUwAHZHQiYAtpjBQmxMkRgBnCV14A6Z3Qpo77LgG0AujIUqgYiCYDZwyJiOqGikAEQAMgDyAOJsAKJmmFRgaIgmzNiOsVJKQcohNlBamDYgyFUAvIiU1LQMFiSOEAzIpNY2Ti5uNlIA3KVlFeGR0XFJqYhpIjCwOXkElkUlZcraUCAUSNq19eOBAL6KgXsHR7r6hiZmHdjjl-IQ+jY2iAAKWWEkAEVPQTGxKtk0GcVBUoBQQNBKKRQZhwXDaGh-BMgv1HCjEE0UdDlO9AgABaJYPAbEjYtDaAikLE7YIIMIRKLoUgAAwAEphkKheEZOIh8bZEAASWS4lHnRzcsbYy7vWGIHQEsWYADufwBCDiACUEMVxjpHPTMIyxkA).

If you copy-paste the transpiled output into the console, you'll see the expected output mentioned in the official TS 5.0 [announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#decorators).

With that in mind, what do you think is still missing for Stage 3 decorators to be usable in a Vite/React/Typescript project?

**Comment by ArnaudBarre** [comment]
Oh I see. I need to look at how esbuild handles this, but as soon as esbuild also correctly handles the new decorator version for TS (maybe it already does) I will publish a major version that makes tsDecorators default to the standards

**Comment by yay** [comment]
I believe the work hasn't even started in esbuild: https://github.com/evanw/esbuild/issues/104
But SWC shipped with initial support a few days ago. Some work is still outstanding though:
https://github.com/swc-project/swc/discussions/5053#discussioncomment-5543835
https://github.com/swc-project/swc/issues/7193
But from my understanding there's enough there already for decorators to be usable.

**Comment by ArnaudBarre** [comment]
Thanks for the links.
The proposal was merged 6 hours ago 😮

I will wait a week or two to see what API will be shipped in esbuild. Maybe this will be in a breaking version of esbuild, meaning that we will need to wait for Vite core to release a version with it so that the plugin can expect it.

If you want to try output the change in the meantime, you can patch the plugin to pass decoratorVersion to SWC and use `plugins: []` to force the plugin to use SWC at build time so that decorators are transformed by SWC and not esbuild

**Comment by yay** [comment]
> The proposal was merged 6 hours ago

I think it was initially thought to be ready a few months ago, followed by some normative updates:
https://github.com/microsoft/TypeScript/pull/52582
https://github.com/tc39/proposal-decorators/issues/499

> If you want to try output the change in the meantime, you can patch the plugin to pass decoratorVersion to SWC and use plugins: [] to force the plugin to use SWC at build time so that decorators are transformed by SWC and not esbuild

Thank you. I'll give it a try!

**Comment by thenbe** [comment]
Were you able to use ecmascript decorators with vite?

**Comment by uinz** [comment]
If you want to use TS decorator and auto accessor, you can try [unplugin-swc](https://github.com/unplugin/unplugin-swc)


```ts
import { defineConfig } from "vite";
import swc from "unplugin-swc";

export default defineConfig({
  plugins: [
    swc.vite({
      jsc: {
        parser: {
          syntax: "typescript",
          decorators: true,
        },
        transform: {
          decoratorMetadata: true,
          decoratorVersion: "2022-03",
          react: {
            runtime: "automatic",
          },
        },
      },
    }),
  ],
});

```

**Comment by AntonOfTheWoods** [comment]
@uinz can this be used with `vite-plugin-react-swc`, or is it intended to be used instead of it?

**Comment by uinz** [comment]
> @uinz can this be used with `vite-plugin-react-swc`, or is it intended to be used instead of it?

esbuild 0.21.3 has implemented ES decorator, so vite should support it by default.

try lock esbuild version at 0.21.3 (eg pnpm overrides)

**Comment by AntonOfTheWoods** [comment]
> esbuild 0.21.3 has implemented the ES decorator, so vite should support it by default.

I am using typescript so I'm not 100% that this is even directly the cause of my issue but isn't https://github.com/vitejs/vite-plugin-react/issues/314#issuecomment-2105728919 relevant for direct `vite` support?
