### ISSUE TITLE
i have a build error for this plugin

### ISSUE THREAD

**Issue by MrWangJustToDo** [vitejs/vite-plugin-react-swc#89]
![image](https://user-images.githubusercontent.com/57748455/234026867-e0c7d7d8-e23c-48f9-a352-18595b710aca.png)
when i usee `vite-plugin-react`, every thing work fine. but when i switch to use this plugin, i have a build error. i have not idea why this happen. 
here is my repo link [https://github.com/MrWangJustToDo/react-ssr-setup](https://github.com/MrWangJustToDo/react-ssr-setup) 

 - first: clone project & `pnpm install & pnpm run build:packages`
 - then: cd `ui` dir, change `.env` config, `FRAMEWROK=vite   SWC=true`
 - finally: back to project root dir and `pnpm run dev:ui`  this error will happen

hope someone can give me any help, thanks

**Comment by ArnaudBarre** [comment]
Hi,

The difference is that the swc plugin is not "pre" transform, so you need to put it before other plugins in the plugins list so that they don't have parsing issues with JSX

**Comment by MrWangJustToDo** [comment]
thanks a lot!  now everything works perfectly
