### ISSUE TITLE
how to config transform

### ISSUE THREAD

**Issue by eightHundreds** [vitejs/vite-plugin-react-swc#93]
```
// .swcrc
[
    {
      "test": ".tsx?$",
      "jsc": {
        "parser": {
          "syntax": "typescript",
          "tsx": true,
          "decorators": false,
          "dynamicImport": true
        },
        "transform": {
          "react": {
            "throwIfNamespace": false
          }
        }
      }
    },
]
```
this is no work

**Comment by ArnaudBarre** [comment]
Yeah this is not configurable. What is missing for you?

**Comment by nsaunders** [comment]
It would be great to be able to configure `"throwIfNamespace": false`. As far as I can tell, React supports JSX namespaces at least as far back as v17.

**Comment by ArnaudBarre** [comment]
Can you provide an example usage via stackblitz with the Babel version? I'm never encounter them.
If this is something, maybe you should ask to change the default in SWC
