### ISSUE TITLE
incompatible with typescript node16 resolution with `type: module`

### ISSUE THREAD

**Issue by JounQin** [vitejs/vite-plugin-react-swc#95]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/8336744/235679973-bef694b5-2382-4504-915f-ff70facf49f6.png">

This is because `.d.ts` is considered as `commonjs` declaration by default

**Comment by JounQin** [comment]
Workaround: export `react` as named export at the same time, so that the user can use `import { react } from '@vitejs/plugin-react-swc'`

**Comment by ArnaudBarre** [comment]
The vite config is not running in node, so you should use the bundler resolution added in TS 5

**Comment by JounQin** [comment]
> The vite config is not running in node, so you should use the bundler resolution added in TS 5

It can be. Vite can be used as a server middleware.

**Comment by ArnaudBarre** [comment]
yeah but the config will be bundled by Vite

**Comment by JounQin** [comment]
> yeah but the config will be bundled by Vite

It can be loaded by user manually and overrides the vite config accordingly.

---

This issue is about compatibility, I don't understand why you are requesting to change the tsconfig which is used by other tools at the same time.
