### ISSUE TITLE
Segmentation fault using plugins

### ISSUE THREAD

**Issue by Xenfo** [vitejs/vite-plugin-react-swc#97]
Just using a simple plugin such as `@swc/plugin-noop` causes a segfault when trying to load the page in dev mode.

```ts
// vite.config.ts
import react from "@vitejs/plugin-react-swc";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [
    react({
      plugins: [["@swc/plugin-noop", {}]],
    }),
  ],
});
```

**Comment by ArnaudBarre** [comment]
Can you please provide more context about your setup? OS, node version, @swc/core version?

I have a test suite running plugins that runs both on my laptop (Mac Intel) and on Linux on GH actions.

And this plugin is a one file using the node api of SWC in a simple way, so I'm not sure there is anything I can do

**Comment by Xenfo** [comment]
Sorry, this was an issue with the monorepo setup I had, `noop` works now in the new setup and a clean Vite project.
