### ISSUE TITLE
Fast Refresh won't let me export custom hooks i define that follow the rules of hooks

### ISSUE THREAD

**Issue by cowboysr0ck9** [vitejs/vite-plugin-react-swc#98]
// Define the API provider component
function MetadataProvider({ children }: IMetadataGuardProps) {
  const { data, isLoading, isError } = useFetchUserMetadata({
    config: {
      staleTime: Infinity,
    },
  });

  if (isLoading) {
    return <SuspenseFallback customMessage="Loading user metadata..." />;
  }

  if (isError) {
    return <Navigate to="/user/select-profile" />;
  }
  // Render the provider with the API data in the context value
  return (
    <MetadataContext.Provider value={apiData}>
      {children}
    </MetadataContext.Provider>
  );
}

// Define a custom hook to consume the API data
function useMetadata() {
  const usermetadata = useContext(MetadataContext);
  return usermetadata;
}

export { MetadataProvider, useMetadata };

Can someone please point me in the right direction as to why this doesnt't work? I am using vite 4.3.4 and "@vitejs/plugin-react-swc": "3.3.0",

**Comment by ArnaudBarre** [comment]
The issue is not about the rules of hooks, it's about the limitation of fast refresh. You should define your hooks in different files from components to be able to get your component fast refreshed correctly.

Otherwise you can keep the setup and ignore the warning, everything will works fine, just you will probably loose state on hmr updates (and they will be slower)

**Comment by cowboysr0ck9** [comment]
> The issue is not about the rules of hooks, it's about the limitation of fast refresh. You should define your hooks in different files from components to be able to get your component fast refreshed correctly.
> 
> Otherwise you can keep the setup and ignore the warning, everything will works fine, just you will probably loose state on hmr updates (and they will be slower)

Thank you very much, and I am just switching to this fast refresh any pointers as to why certain things completely remount and lose their state? I am having a very difficult time debugging it currently. I am using a very basic redux store with react router dom and the entire state tree reloads every time on certain pages now that i switched to fast refresh so just curious to what causes this or if there is documentation.

**Comment by ArnaudBarre** [comment]
You can use https://github.com/ArnaudBarre/eslint-plugin-react-refresh
More read on this is available on the [next.js doc](https://nextjs.org/docs/basic-features/fast-refresh) or the [Gastby doc](https://nextjs.org/docs/basic-features/fast-refresh) (There is no official doc on this from the core team yet)
